## General settings
load_libraries: [
  'bookdown', 'data.table', 'glue', 'knitr', 'R6', 'rmarkdown', 'rticles', 'tinytex',
  'yaml'
]
tex_style:
  standalone: 'article'
  thesis: 'ociamthesis'
## Chapter and section titles
title:
  thesis: ''
  test_chapter: 'My test chapter title'
  italy: ''

## Options that will be passed directly to the bookdown config
bookdown_options:
  bibliography: '/home/nat/Documents/Dropbox/Writing/Mendeley-export-20210511.bib'
  citation_package: 'biblatex'
  biblatexoptions: '[style=nature, citestyle=draft]'
  link-citations: true
  github-repo: 'nathenry/thesis'

## Directories (used to resolve brackets in filepaths below)
dirs:
  repo: '~/repos/thesis'
  thesis_docs: '~/Documents/Dropbox/Writing/thesis_resources'
  graphics: '~/Documents/Dropbox/Writing/thesis_resources/graphics'
  thesis_data: '~/Documents/Dropbox/Writing/thesis_resources/data'

## Filepaths: Graphics
graphics_fps:
  test_chapter:
    fig1: '{graphics}/test_chapter/fig1.png'

## Filepaths: Input data (to be loaded as tables)
data_fps:
  test_chapter:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
    t2: '{thesis_data}/test_chapter/t2_test.csv'
