## General settings
load_libraries: [
  'bookdown','data.table','dplyr','glue','knitr','kableExtra','R6','rmarkdown','rticles',
  'tinytex','yaml'
]
tex_style:
  standalone: 'article'
  thesis: 'ociamthesis'
preprint: true

## Options that will be passed directly to the bookdown config
bibliography: '{thesis_docs}/bibliographies/Mendeley-export-20211206.bib'
citation_style: 'nature'
link-citations: true
github-repo: 'nathenry/thesis'

## Directories (used to resolve brackets in filepaths below)
dirs:
  repo: 'C:/Users/nathenry/Documents/repos/thesis'
  thesis_docs: 'C:/Users/nathenry/Dropbox/Writing/thesis'
  graphics: 'C:/Users/nathenry/Dropbox/Writing/thesis/graphics'
  thesis_data: 'C:/Users/nathenry/Dropbox/Writing/thesis/data'

## Filepaths: Graphics
graphics_fps:
  introduction:
    fig1: '{graphics}/introduction/fig1_CRVS_under_5_mortality_completeness.png'
  india:
    flowchart: '{graphics}/flowcharts/india_v2.png'
    mort_2000_2017: "{graphics}/india/fig1_mort_2000_2017.png"
    u5m_aroc_2000_2017: "{graphics}/india/fig2_u5m_aroc_2000_2017.png"
    hilo_all_ages: "{graphics}/india/fig3_hilo_all_ages.png"
    u5m_proj_2025: "{graphics}/india/fig4_u5m_proj_2025.png"
    srs_comparison: "{graphics}/india/fig5_srs_comparison.png"
    sample_size: "{graphics}/india/fig6_sample_size.png"
    rankings: "{graphics}/india/fig7_rankings.png"
  india_appx:
    cov_access: "{graphics}/india/IND_access2_2000_2017_maps.png"
    cov_ntl: "{graphics}/india/IND_dmspntl_2000_2017_maps.png"
    cov_dpt3: "{graphics}/india/IND_dpt3_cov_2000_2017_maps.png"
    cov_edu: "{graphics}/india/IND_edu_mean_stage2_gadm_2000_2017_maps.png"
    cov_u5_women_ratio: "{graphics}/india/IND_fertility_2000_2017_maps.png"
    cov_urbanicity: "{graphics}/india/IND_ghslurbanicity_2000_2017_maps.png"
    cov_pm25: "{graphics}/india/IND_ihmepm25_2000_2017_maps.png"
    cov_pf: "{graphics}/india/IND_map_pf_incidence_2000_2017_maps.png"
    cov_stunting: "{graphics}/india/IND_stunting_mod_b_2000_2017_maps.png"
    cov_pop_density: "{graphics}/india/IND_worldpop_2000_2017_maps.png"
  mexico:
    capture_recapture: '{graphics}/mexico/capture_recapture.png'
    flowchart: '{graphics}/flowcharts/mexico_v2.png'
    excl_groups: '{graphics}/mexico/excl_groups.png'
    excl_covs: '{graphics}/mexico/excl_covs.png'
    sim_results: '{graphics}/mexico/sim_results.png'
    nmr_wide_model: '{graphics}/mexico/nmr_wide_model.png'
    vr_bias_wide_model: '{graphics}/mexico/vr_bias_wide_model.png'
    crvs_bias_diff: '{graphics}/mexico/crvs_bias_diff.png'
  italy:
    covid_deaths: '{graphics}/italy/fig1_covid_deaths.png'
    time_series: '{graphics}/italy/fig2_time_series.png'
    age_excess: '{graphics}/italy/fig3_age_excess.png'
    age_maps: '{graphics}/italy/fig4_age_maps.png'
    top_provinces: '{graphics}/italy/fig5_top_provinces.png'
    excess_neighbors: '{graphics}/italy/fig6_excess_neighbors.png'
  italy_thesis:
    covid_deaths: '{graphics}/italy/fig1_covid_deaths.png'
    flowchart: '{graphics}/flowcharts/italy_v2.png'
    time_series: '{graphics}/italy/fig2_time_series.png'
    age_excess: '{graphics}/italy/fig3_age_excess.png'
    age_maps: '{graphics}/italy/fig4_age_maps.png'
    top_provinces: '{graphics}/italy/fig5_top_provinces.png'
    excess_neighbors: '{graphics}/italy/fig6_excess_neighbors.png'
    excess_ratio: '{graphics}/italy/fig7_excess_ratio.png'
  uganda:
    flowchart: '{graphics}/flowcharts/uganda_v2.png'
    uga_map: '{graphics}/uganda/uga_major_cities.png'
    data_prev_survey: '{graphics}/uganda/data_prev_survey.png'
    data_case_notifs: '{graphics}/uganda/data_case_notifs.png'
    prev_scatter: '{graphics}/uganda/prev_scatter.png'
    notif_completeness: '{graphics}/uganda/notif_completeness.png'
    average_duration: '{graphics}/uganda/average_duration.png'
    prev_notifs_diff: '{graphics}/uganda/prev_notifs_diff.png'
    thresh_comparison: '{graphics}/uganda/thresh_comparison.png'
  uganda_appx:
    prev_scatter_d_1: '{graphics}/uganda/prev_scatter_d_1.png'
    notif_completeness_d_1: '{graphics}/uganda/notif_completeness_d_1.png'
    prev_scatter_d_ihme: '{graphics}/uganda/prev_scatter_d_ihme.png'
    notif_completeness_d_ihme: '{graphics}/uganda/notif_completeness_d_ihme.png'
  discussion:
    summary_map: '{graphics}/discussion/summary_map_2021-09-27.png'
  test_chapter:
    fig1: '{graphics}/test_chapter/fig1.png'

## Filepaths: Input data (to be loaded as tables)
data_fps:
  introduction:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
  india:
    data_sources: '{thesis_data}/india/t1_india_data_sources.csv'
  mexico:
    priors: '{thesis_data}/mexico/priors.csv'
    sim_param_results: '{thesis_data}/mexico/sim_param_results.csv'
  mexico_appx:
    moderately_marginalized: '{thesis_data}/mexico/moderately_marginalized.csv'
    severely_marginalized: '{thesis_data}/mexico/severely_marginalized.csv'
  italy:
    covariates_table: '{thesis_data}/italy/t1_covariates_table.csv'
    excess_demographics: '{thesis_data}/italy/t2_excess_demographics.csv'
  italy_thesis:
    covariates_table: '{thesis_data}/italy/t1_covariates_table.csv'
    excess_demographics: '{thesis_data}/italy/t2_excess_demographics.csv'
  italy_appx:
    covariates_table: '{thesis_data}/italy/appendix_covariates_table.csv'
    ispv_by_obs_table: '{thesis_data}/italy/appendix_ispv_by_obs_table.csv'
    ispv_by_group_table: '{thesis_data}/italy/appendix_ispv_by_group_table.csv'
    oospv_by_obs_table: '{thesis_data}/italy/appendix_oospv_by_obs_table.csv'
    oospv_by_group_table: '{thesis_data}/italy/appendix_oospv_by_group_table.csv'
  uganda:
    who_duration_groupings: '{thesis_data}/uganda/who_duration_groupings.csv'
  uganda_appx:
    duration_scenarios: '{thesis_data}/uganda/duration_scenarios.csv'
    sensitivity_testing_results: '{thesis_data}/uganda/sensitivity_testing_results.csv'
  discussion:
    t1: '{thesis_data}/test_chapter/t1_test.csv'

  test_chapter:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
    t2: '{thesis_data}/test_chapter/t2_test.csv'
