## General settings
load_libraries: [
  'bookdown','data.table','dplyr','glue','knitr','kableExtra','R6','rmarkdown','rticles',
  'tinytex','yaml'
]
tex_style:
  standalone: 'article'
  thesis: 'ociamthesis'
preprint: true

## Options that will be passed directly to the bookdown config
bibliography: '{thesis_docs}/bibliographies/Mendeley-export-20210909.bib'
citation_style: 'nature'
link-citations: true
github-repo: 'nathenry/thesis'

## Directories (used to resolve brackets in filepaths below)
dirs:
  repo: 'C:/Users/nathenry/Documents/repos/thesis'
  thesis_docs: 'C:/Users/nathenry/Dropbox/Writing/thesis'
  graphics: 'C:/Users/nathenry/Dropbox/Writing/thesis/graphics'
  thesis_data: 'C:/Users/nathenry/Dropbox/Writing/thesis/data'

## Filepaths: Graphics
graphics_fps:
  introduction:
    fig1: '{graphics}/introduction/fig1_CRVS_under_5_mortality_completeness.png'
  india:
    mort_2000_2017: "{graphics}/india/fig1_mort_2000_2017.png"
    u5m_aroc_2000_2017: "{graphics}/india/fig2_u5m_aroc_2000_2017.png"
    hilo_under5: "{graphics}/india/fig3_hilo_under5.png"
    u5m_proj_2025: "{graphics}/india/fig4_u5m_proj_2025.png"
    srs_comparison: "{graphics}/india/fig5_srs_comparison.png"
    sample_size: "{graphics}/india/fig6_sample_size.png"
    rankings: "{graphics}/india/fig7_rankings.png"
  mexico:
    capture_recapture: '{graphics}/mexico/capture_recapture.png'
    excl_groups: '{graphics}/mexico/excl_groups.png'
    excl_covs: '{graphics}/mexico/excl_covs.png'
    sim_results: '{graphics}/mexico/sim_results.png'
    nmr_wide_model: '{graphics}/mexico/nmr_wide_model.png'
    vr_bias_wide_model: '{graphics}/mexico/vr_bias_wide_model.png'
    crvs_bias_diff: '{graphics}/mexico/crvs_bias_diff.png'
  italy:
    covid_deaths: '{graphics}/italy/fig1_covid_deaths.png'
    time_series: '{graphics}/italy/fig2_time_series.png'
    age_excess: '{graphics}/italy/fig3_age_excess.png'
    age_maps: '{graphics}/italy/fig4_age_maps.png'
    top_provinces: '{graphics}/italy/fig5_top_provinces.png'
    excess_neighbors: '{graphics}/italy/fig6_excess_neighbors.png'
  italy_thesis:
    covid_deaths: '{graphics}/italy/fig1_covid_deaths.png'
    time_series: '{graphics}/italy/fig2_time_series.png'
    age_excess: '{graphics}/italy/fig3_age_excess.png'
    age_maps: '{graphics}/italy/fig4_age_maps.png'
    top_provinces: '{graphics}/italy/fig5_top_provinces.png'
    excess_neighbors: '{graphics}/italy/fig6_excess_neighbors.png'
    excess_ratio: '{graphics}/italy/fig7_excess_ratio.png'
  uganda:
    prev_scatter: '{graphics}/uganda/prev_scatter.png'
    notif_completeness: '{graphics}/uganda/notif_completeness.png'
    notif_prev_ratio: '{graphics}/uganda/notif_prev_ratio.png'
    prev_notifs_diff: '{graphics}/uganda/prev_notifs_diff.png'
  discussion:
    fig1: '{graphics}/test_chapter/fig1.png'
  test_chapter:
    fig1: '{graphics}/test_chapter/fig1.png'

## Filepaths: Input data (to be loaded as tables)
data_fps:
  introduction:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
  india:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
  mexico:
    sim_param_results: '{thesis_data}/mexico/sim_param_results.csv'
  italy:
    covariates_table: '{thesis_data}/italy/t1_covariates_table.csv'
    excess_demographics: '{thesis_data}/italy/t2_excess_demographics.csv'
  italy_thesis:
    covariates_table: '{thesis_data}/italy/t1_covariates_table.csv'
    excess_demographics: '{thesis_data}/italy/t2_excess_demographics.csv'
  uganda:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
  discussion:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
  test_chapter:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
    t2: '{thesis_data}/test_chapter/t2_test.csv'
