## General settings
load_libraries: [
  'bookdown', 'data.table', 'glue', 'knitr', 'R6', 'rmarkdown', 'tinytex', 'yaml'
]
tex_style:
  standalone: 'article'
  thesis: 'ociamthesis'
cite_style:
  standalone: 'nature'
  thesis: 'nature'
## Chapter and section titles
title:
  thesis: ''
  test_chapter: 'My test chapter title'
  italy: ''
bibtitle:

## Directories (used to resolve brackets in filepaths below)
dirs:
  repo: '~/repos/thesis'
  thesis_docs: '~/Documents/Dropbox/Writing/thesis_resources'
  graphics: '~/Documents/Dropbox/Writing/thesis_resources/graphics'
  thesis_data: '~/Documents/Dropbox/Writing/thesis_resources/data'

## Filepath for the .bib file used across all chapters
bibtex_fp : '{thesis_docs}/bibliographies/Mendeley_export_20210511.bib'

## Filepaths: Graphics
graphics_fps:
  test_chapter:
    fig1: '{graphics}/test_chapter/fig1.png'

## Filepaths: Input data (to be loaded as tables)
data_fps:
  test_chapter:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
    t2: '{thesis_data}/test_chapter/t2_test.csv'
