   ## General settings
load_libraries: [
  'bookdown','data.table','dplyr','glue','knitr','kableExtra','R6','rmarkdown','rticles',
  'tinytex','yaml'
]
tex_style:
  standalone: 'article'
  thesis: 'ociamthesis'
preprint: true

## Options that will be passed directly to the bookdown config
bibliography: '{thesis_docs}/bibliographies/Mendeley-export-20210511.bib'
citation_style: 'nature'
link-citations: true
github-repo: 'nathenry/thesis'

## Directories (used to resolve brackets in filepaths below)
dirs:
  repo: '/home/nat/repos/thesis'
  thesis_docs: '/home/nat/Documents/Dropbox/Writing/thesis'
  graphics: '/home/nat/Documents/Dropbox/Writing/thesis/graphics'
  thesis_data: '/home/nat/Documents/Dropbox/Writing/thesis/data'

## Filepaths: Graphics
graphics_fps:
  introduction:
    fig1: '{graphics}/test_chapter/fig1.png'
  india:
    fig1: '{graphics}/test_chapter/fig1.png'
  mexico:
    fig1: '{graphics}/test_chapter/fig1.png'
  italy:
    covid_deaths: '{graphics}/italy/fig1_covid_deaths.png'
    time_series: '{graphics}/italy/fig2_time_series.png'
    age_excess: '{graphics}/italy/fig3_age_excess.png'
    age_maps: '{graphics}/italy/fig4_age_maps.png'
    top_provinces: '{graphics}/italy/fig5_top_provinces.png'
    excess_neighbors: '{graphics}/italy/fig6_excess_neighbors.png'
  uganda:
    fig1: '{graphics}/test_chapter/fig1.png'
  discussion:
    fig1: '{graphics}/test_chapter/fig1.png'
  test_chapter:
    fig1: '{graphics}/test_chapter/fig1.png'

## Filepaths: Input data (to be loaded as tables)
data_fps:
  introduction:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
  india:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
  mexico:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
  italy:
    covariates_table: '{thesis_data}/italy/t1_covariates_table.csv'
    excess_demographics: '{thesis_data}/italy/t2_excess_demographics.csv'
  uganda:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
  discussion:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
  test_chapter:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
    t2: '{thesis_data}/test_chapter/t2_test.csv'
