## General settings
load_libraries: [
  'bookdown', 'data.table', 'glue', 'knitr', 'R6', 'rmarkdown', 'rticles', 'tinytex',
  'yaml'
]
tex_style:
  standalone: 'article'
  thesis: 'ociamthesis'
preprint: true
## Chapter and section titles
title:
  thesis: ''
  test_chapter: 'My test chapter title'
  italy: ''

## Options that will be passed directly to the bookdown config
bibliography: '{thesis_docs}/bibliographies/Mendeley-export-20210511.bib'
citation_style: 'nature'
link-citations: true
github-repo: 'nathenry/thesis'

## Directories (used to resolve brackets in filepaths below)
dirs:
  repo: '/home/nat/repos/thesis'
  thesis_docs: '/home/nat/Documents/Dropbox/Writing/thesis'
  graphics: '/home/nat/Documents/Dropbox/Writing/thesis/graphics'
  thesis_data: '/home/nat/Documents/Dropbox/Writing/thesis/data'

## Filepaths: Graphics
graphics_fps:
  test_chapter:
    fig1: '{graphics}/test_chapter/fig1.png'

## Filepaths: Input data (to be loaded as tables)
data_fps:
  test_chapter:
    t1: '{thesis_data}/test_chapter/t1_test.csv'
    t2: '{thesis_data}/test_chapter/t2_test.csv'
