%
% Example knitR + LaTeX code from a tutorial: http://edrub.in/ARE212/latexKnitr.html
%

\documentclass[english, 11pt]{article}

\usepackage[utf8]{inputenc}

\usepackage{setspace}
\onehalfspacing

\title{My beautiful PDF document}
\author{Nathaniel Henry}
\date{7 May 2021}

\begin{document}

\begin{titlepage}
\maketitle
\end{titlepage}

\noindent What a beautiful PDF!

\section{Paragraphs, text, and lists}

\subsection{Paragraphs}

\textit{An excerpt from \underline{The War of the Worlds} (Book I), by H. G. Wells}

For the main road was a boiling stream of people, a torrent of human beings rushing
northward, one pressing on another. A great bank of dust, white and luminous in the
blaze of the sun, made everything within twenty feet of the ground grey and
indistinct and was perpetually renewed by the hurrying feet of a dense crowd of
horses and of men and women on foot, and by the wheels of vehicles of every description.

``Way!'' my brother heard voices crying. ``Make way!''

It was like riding into the smoke of a fire to approach the meeting point of the lane
and road; the crowd roared like a fire, and the dust was hot and pungent. And, indeed,
a little way up the road a villa was burning and sending rolling masses of black smoke
across the road to add to the confusion.

\subsection{Lists}

Let's make a list!

\subsubsection*{An unnumbered list of random things}

\begin{itemize}
  \item Econometrics
  \item Pastrami
  \item Garden gnomes
  \item Redwoods
\end{itemize}

\subsubsection*{A numbered list}

\noindent The hierarchy of fruit deliciousness

\begin{enumerate}
  \item Raspberry
  \item Cherry
  \item Kiwi
  \item \ldots
  \item Apple
\end{enumerate}

\textbf{Note:} This hierarchy does not pertain to pies.

% knitR examples begin here
\section{Let's try out `knitR`}

Time for some smart code!

\subsection{Show code execution}

Here's some text before the code block.

<<>>=
print("Hello world")
@

Here's some text after the code block. This text is going to be fairly long to show that, in fact, carriage returns after the first paragraph lead to auto-indented future paragraphs.

\subsection{Use an output from quiet code execution}

<<exec = T, echo = FALSE>>=
var_a <- 500
var_b <- 2
test_sum <- var_a + var_b
@

Fun math fact: \Sexpr{var_a} plus \Sexpr{var_b} equals \Sexpr{test_sum}.

\end{document}
