%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Testing code to set compile parameters using a YAML config file
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% SETUP: Config is imported by the executing R script ---------------------------------->

\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage{setspace}

%% TEST: Can we set LaTeX options and arguments using the config?
  \usepackage[backend=bibtex, style=\Sexpr{conf$citestyle}]{biblatex}
\addbibresource{\Sexpr{conf$bibtex_fp}}

\onehalfspacing
\title{\Sexpr{conf$test_title}}
\author{Nathaniel Henry}
\date{\today}

\begin{document}

\begin{titlepage}
\maketitle
\end{titlepage}

\section{Config to text}

Let's see what the config value is: \Sexpr{conf$test_val}. For a reference, see \parencite{Aalbers2014, \Sexpr{conf$cite_val}}.

\printbibliography

\end{document}
