<<exec = FALSE, echo = FALSE>>=
  ## #####################################################################################
  ##
  ## RNW TEMPLATE FOR A THESIS TEST ARTICLE/CHAPTER
  ##
  ## AUTHOR: Nathaniel Henry
  ## CREATED: 20 May 2021
  ## PURPOSE: Content template for a test chapter
  ##
  ## EXECUTION: This file is compiled using the runner script (one of
  ##     `compile_single_chapter.R` or `compile_full_thesis.R`).
  ##  1) This RNW content file is knitted into TEX stub by the runner script. It requires
  ##     the following objects to be present in the runner script environment:
  ##     - `conf` (R6 object, list-like): Configuration object for all chapters
  ##     - `chapter` (char): Chapter name, corresponding to headers in `conf`
  ##     - `data_list` (list): List of data.frames for number-plugging
  ##     - `graphics_fps` (list): List of valid character filepaths for figures
  ##  2) After knitting, the runner script will incorporate this stub into a full TEX
  ##     document (possibly alongside other stubs) and will then render the full document
  ##     as a PDF.
  ##
  ## #####################################################################################
@

%% Note that this example is taken from an Overleaf tutorial: https://bit.ly/3wjYP1W
%% Used in accordance with CC BY 4.0 license

%%%%%% Abstract %%%%%%
\begin{abstract}
The abstract should be a single paragraph written in plain language that a general
reader can understand. Use a Structured Abstract with the sections indicated below. Do
not include citations or undefined abbreviations in the abstract. Any abbreviations that
appear in the title should be defined in the abstract. The length should not exceed 250
words. The sections to include are:
\begin{itemize}
    \item Objective: An opening sentence that states the objective of the research
    \item Impact Statement: Brief description about the novelty and impact of the research
    \item Introduction: Enough background information to give context to the study
    \item Methods: A brief statement of the primary methods used by the study
    \item Results: A brief statement of primary results
    \item Conclusion: A short concluding sentence of the main take-home point(s) of the study
\end{itemize}
\end{abstract}

%%%%%% Main Text %%%%%%

\section{Introduction}
Your manuscript should contain all of the numbered sections specified in this template:
Introduction, Results, Discussion, Materials and Methods.

The manuscript should start with a brief introduction that lays out the problem addressed
by the research and describes the paper’s importance. The scientific question being
investigated should be described in detail. The introduction should provide sufficient
background information to make the article understandable to readers in other disciplines
and provide enough context to ensure that the implications of the experimental findings
are clear. Here's an example citation\cite{Aalbers2014}.

%%%%%% Equations %%%%%%
\subsection*{Equations}
Equations should be provided in a text format, rather than as an image. Equations should
be numbered consecutively, in round brackets, on the right-hand side of the page by using
the ``\textbackslash begin\{equation\}'' command. They should be referred to as Equation
1, etc. in the main text.

\medskip For example, see Equation \ref{eq:1} below.
\begin{equation} \label{eq:1}
    a^2 + b^2 = c^2
\end{equation}


%%%%%% Tables %%%%%%
\subsection*{Tables}
Tables should supplement, not duplicate, the text. They should be called out
consecutively within the text and numbered in the order of their citation in the text.

Every table must have a descriptive title beginning with ``Table [Number] …'' as noted
in Table \ref{tab:1}. If numerical measurements are given, the units should be included
in the column heading. Every vertical column should have a heading, followed by a unit
of measure (if any) in parentheses. Units should not change within a column. Vertical
rules should not be used.

Centered headings of the body of the table can be used to break the entries into groups.
Do not use footnotes in column heads; include any such details in sentence form in the
table legend. Footnotes should contain information relevant to specific cells of the
table; use the following symbols in order, as needed: $*, \dag, \ddag, \S, \|, \P, \#,
**, \dag\dag$, etc.

\begin{table}[b]
    \caption{This is an example table.}
    \centering
    \begin{tabular}{ccc}
            \hline
            Column 1 & Column 2 & Column 3 \\
            \hline
            Cell 1 & Cell 2 & Cell 3\\
            Cell 4 & Cell 5 & Cell 6 \\
            \hline
            \end{tabular}

    \label{tab:1}
\end{table}

\section{Results}
The results should describe the experiments performed and the findings observed. The
results section should be divided into subsections to delineate different experimental
themes. Subheadings should either be all phrases or all complete sentences. All data
must be shown either in the main text or in the Supplementary Materials.
\begin{itemize}
    \item All data, both that in the main part of the manuscript and that in the Supplementary Materials, should be presented in the Results. No data should be presented for the first time in the Discussion. Data (such as from Western blots) should be appropriately quantified from multiple independent experiments. Inclusion of biological data from individual experiments that have not been repeated at least twice is generally not permitted.
    \item Subheadings must be either all complete sentences or all phrases. They should be brief, ideally less than 10 words. Subheadings should not end in a period. The Results section may have as many level 1 subheadings as are necessary.
    \item Figures and tables must be called out in numerical order. For example, the first mention of any panel of Figure 3 cannot precede the first mention of all panels of Figure 2. The supplementary figures (for example, Figure S1) and tables (Table S1) must also be called out in numerical order. All figures and tables should have a title and a legend.
    \item Mathematical expressions within a sentence of text should be created with ordinary Word characters; if this is not possible, then use MathType (or the equivalent). Only use MathType when necessary — for example, characters with overbars or carets, with stacked superscripts and subscripts, or within square root symbols.
\end{itemize}

\section{Discussion}
Include a Discussion that summarizes (but does not merely repeat) your conclusions and
elaborates on their implications. There should be a paragraph outlining the limitations
of your results and interpretation, as well as a discussion of the steps that need to be
taken for the findings to be applied. Please avoid claims of priority.

\section{Materials and Methods}
The materials and methods section should provide sufficient information to allow
replication of the rsesults. This section should be broken up by subheadings. Under
exceptional circumstances, when a particularly lengthy description is required, a
portion of the materials and methods can be included in the Supplementary Materials.
