---
title: "Discussion"
author: "Nathaniel Henry"
date: "`r Sys.Date()`"
documentclass: "`r conf$v$tex_style[[chapter_type]]`"
bibliography: "`r conf$v$bibliography`"
csl: "`r paste0(conf$v$citation_style, '.csl')`"
link-citations: true
---

```{r set_captions, echo=FALSE}
knitr::opts_chunk$set(fig.pos = "!ht", out.extra = "", fig.align = 'center', echo=FALSE)

# Set caption text
captions <- list(
  fig1 = "Example caption for a figure.",
  t1 = "Example caption for a table."
)
```

PAR: What was the point of this thesis?

In this thesis, I develop a class of methods to make health surveillance data interpretable and policy-relevant at the local level. To do so, I extend traditional geostatistical and small-area estimation approaches to synthesize two or more health data sources, compensating for the limitations of each individual data type in the process. In four national case studies, I tailor this framework to accommodate country-specific data gaps, disease contexts, and existing programmatic needs. Because the resulting models identify local variation in surveillance completeness across a country, they offer a method for correcting raw surveillance data among small sub-populations, increasing the usability of this data for public health policy. Health surveillance completeness is also a measure of health system performance in its own right, and these estimates can be further used to target future health surveillance improvements, supplementing local audits that can be prohibitively expensive to implement nationwide. I demonstrate that this framework can also be applied to understand health surveillance gaps in high-income countries, which previous research has often treated as complete.

This discussion summarizes key findings from each chapter of the thesis, synthesizes the methods used across country contexts, and links this research to active debates in global health. I also discuss the strengths and limitations of this research, and describe considerations for communicating this class of models in a policy-oriented context. In light of these considerations, I suggest future methodological work and applications that can further improve our understanding of health surveillance data.


# Chapter summary

The thesis begins with a description of data types commonly used to estimate disease burden and their known limitations for estimating health at the local level. Chapter 2 identifies the core issue of latent, spatially-varying bias as a barrier to utilization of health surveillance data at the local level. This chapter describes past approaches used to estimate bias in Civil Registration and Vital Statistics (CRVS) systems[@ChandraSekar1949;@Yip1995; @Becker1996;@DeFrias2013;@Murray2010], as well as the limitations of these approaches for spatial analysis.[@Tilling2001; @Cormack1999; @Schmertmann2018a] I then introduce a new approach to jointly estimate age-specific mortality and CRVS incompleteness at the district level. This approach extends previous research on Bayesian small area estimation for mortality[@Schmertmann2018a; @Wakefield2019] by estimating the ratio between survey-based and routinely-collected data sources, subject to priors about the relationship between these sources. I apply this model to estimate the neonatal mortality rate (NMR) by municipality in Mexico. Context-specific priors for CRVS bias were applied based on previous research that demonstrated birth and death under-reporting in indigenous and socially-marginalized communities across Mexico.[@Hernandez2012; @Enciso2017; @Ribotta2019; @Paulino2019]

While strong priors are appropriate to a data context where health surveillance is nearly complete nationwide, the same class of model can applied in an infectious disease context where case notification completeness is known to be largely incomplete and variable across the country. In the context of global tuberculosis (TB) control, disaggregated estimates of TB prevalence and incidence are highly desirable for national TB control programs (NTPs) as a tool for targeting interventions and identifying treatment gaps.[@Glaziou2018a] In Chapter 3, I explore the TB data context in Uganda, which is representative of the situation in many high-burden countries: while TB case notifications from routine diagnosis are collected and reported annually by the National TB and Leprosy Control Programme (NTLP), these notifications are known to vary in completeness due to gaps in the reporting cascade, making unadjusted notifications an inappropriate proxy for subnational variation in TB incidence.[@Rood2019; @Shaweno2018] A national TB prevalence survey conducted in 2014-2015 does not suffer from the same underreporting bias, but this surveys was not powered for subnational estimation.[@UgandaMinistryofHealth2015] I present a spatial model that combines these data types to generate small-area estimates of both TB prevalence and case notification completeness by district. The resulting model reports subnational prevalence with greater precision than a model based on survey data alone, allowing for more precise tracking of high-burden regions within the country. Additionally, the Uganda NTLP can use estimates of notification completeness at the district level to track progress towards their strategic goal of complete TB case reporting nationwide.[UgandaNationalTuberculosisandLeprosyProgramme2020a]

While reporting completeness is a crucial measure of health data quality, routine surveillance data must meet several other criteria before it can be useful for policymaking at the local level. The United Nations _Principles and Recommendations for a Vital Statistics System_ proposes that CRVS (and other health surveillance data) should also meet stringent standards for timeliness, accuracy in reporting outcomes, and confidentiality.[@UnitedNationsStatisticsDivision2014] In addition to their utility for policy, CRVS birth and death certification enable legal rights for covered individuals.[@Setel2007; @Duryea2006] In Chapter 4, I evaluate three overlapping mortality surveillance programs in India against these standards of quality and utility, as well as their alignment with the goals of India's National Health Plan (NHP) 2017. The household survey series conducted by the Indian government have an unparalleled sample size worldwide, allowing for disaggregated analysis of neonatal, infant, and child mortality using a novel space-time-age modeling framework.[@Dandona2016; @Dandona2020] This analysis demonstrates the value of spatial modeling to monitor progress towards NHP child survival goals; however, it also reveals the limitations of survey-based spatial models even in highly data-rich contexts. Because retrospective survey data on child mortality is most sparse in later years, uncertainty is greatest in the most recent year of analysis and in future projections. India's Sample Registration System, the second surveillance program for child health, is collected annually and includes larger sample sizes, making it a more timely and precise tool for health policy; also, unlike household surveys, the SRS collects data on mortality across adult age groups.[@CensusofIndia2017] Previous analyses have underlined the variable completeness of the SRS at the state level.[@Bhat2002; @Mahapatra2010] In this chapter, I demonstrates how SRS estimates can be adjusted for incompleteness at the district grouping level through comparison to survey-based estimates. If the SRS reported estimated mortality across more disaggregated sub-populations of India, these would enable an equity-focused evaluation of India's progress towards NHP child mortality goals and allow researchers to quickly identify emerging health crises. The third program, India's Civil Registration System (CRS), is the only system designed to provide birth and death certification for all Indian citizens.[@ParliamentoftheRepublicofIndia1969; @Mohanty2018] Ultimately, estimates from India's household survey series and SRS should be used to evaluate progress towards complete certification in the CRS, as this is the only program that can guarantee the rights associated with birth and death registration.[@Abouzahr2007]

Previous geospatial and small-area research has drawn a distinction between incomplete and complete data systems. Research in low- and middle-income countries has often assumed incompleteness in health surveillance systems, requiring epidemiologists to develop corrections for reporting or otherwise limit their analyses.[@Shaweno2018; @Adair2018; @Zeng2020] Conversely, in high-income countries, spatial analyses often treat health surveillance as complete, needing correction only for stochastic fluctuations associated with small sample sizes.[@Papoila2014; @Boing2020] In Chapter 5, I challenge this assumption by investigating spatial variation in excess mortality across Italy during the first months of the COVID-19 pandemic. I use all-cause mortality data from 2015-2019 to estimate baseline mortality by age group, province, and week of the year from March through May 2020; I then compare estimated excess deaths across these groupings to recorded deaths assigned to COVID-19. I find that cause of death reporting for COVID-19 missed 30% of the true disease burden nationwide, and 42% of true disease burden in the provinces where excess mortality was highest. This finding challenges the assumption that health surveillance systems in high-income countries can be interpreted as uniformly complete and accurate. A wider array of tools is needed, including the models proposed in this thesis, to correct for underlying biases in health surveillance data at the local level.


# Methodological discussion

This section reviews the statistical methods used across the chapters, highlighting strengths and limitations of this class of models. 


## Methodological strengths

Small area estimation and geostatistical methods can measure mortality and disease burden at the scale that is most programmatically relevant for health system management. In recent years, national and international health policy documents have stressed the importance of equity in delivering and sustaining health.[@IND_MOHFW2017; @UgandaNationalTuberculosisandLeprosyProgramme2020a; @Buyum2020] Measurement facilitates management: tracking health status across social and geographical groupings can identify inequity, prompting responsive health policy and reform.[@Roberts2008; @Frenk2006] Small area estimation can also offer metrics for understanding program effectiveness at the same scale where money is disbursed and programs implemented, revealing patterns that might be obscured at the national level. Because these models are designed to accommodate data with small sample sizes,[@Diggle2016; @Wakefield2019] they can be extended to measure differences across other dimensions such as age group, as demonstrated in Chapters 4 and 5, without any adjustments to correct for stochastic noise.

Country-specific models of health can be parameterized so that model terms directly reflect quantities of programmatic interest, as demonstrated by the case studies in this thesis. In Mexico, both birth and neonatal death reporting are estimated to be incomplete among some municipalities,[@Hernandez2012; @Enciso2017] so the geostatistical model was implemented with a strictly-positive bias term to show the relative completeness between these two data sources. In Uganda, incompleteness in case reporting was a key metric for the NTLP,[@UgandaNationalTuberculosisandLeprosyProgramme2020] and was expected to outweigh bias in modeled estimates of population denominators in most districts: to best accommodate program needs, under-reporting was directly estimated as a quantity varying between 0 and 1 by district, allowing for the estimation of notification completeness as well as change over time. In India, a model was implemented to track mortality across age groups to track progress towards separate goals for neonatal, infant, and child survival. Within this framework, priors for each country-specific model incorporated expert knowledge and past evidence on the distribution of disease etiology and surveillance reporting across the country. The flexibility of these models allows them to be adapted for country-specific needs, increasing interpretability and utility for developing policy.

In low- and middle-income contexts, small-area modeling offers can supplement existing approaches that have been used to estimate health surveillance data completeness. Local audits have been developed to estimate the completeness of CRVS data and infectious disease notifications;[@DeFrias2013; @Szwarcwald2014; @DeAlmeida2017a; @NationalAdminstrativeDepartmentofStatisticsDANE2006; @Hernandez2012] While these studies ofer a high-quality estimate of completeness in a small number of communities, they are prohibitively expensive to implement nationwide. Completeness audits can easily be integrated into the framework described in this thesis to offer a more representative estimate of completeness nationwide that also incorporates survey and CRVS or notification data. This data synthesis approach is preferred over the previous capture-recapture method, which makes unrealistically strong assumptions about independence between data sources.[@Tilling2001; @Cormack1999]

Finally, the Bayesian hierarchical modeling approach deployed here propagates uncertainty from input data and parameter fits in a principled way, allowing for nuanced analysis about the confidence of results.[@McElreath2016] By saving the structured uncertainty in the resulting model fits, these estimates can be used as principled prior estimates for future analyses. The confidence of district-level estimates can also be visualized and evaluated against programmatically-relevant goals: for example, the uncertainty "draws" generated by this class of models can be compared to a disease reduction target to determine which districts fall below a target threshold in 95% of potential model realizations.[@Patil2011]


## Methodological limitations

Despite their flexibility, this class of semiparametric estimation techniques relies on assumptions that may bias model results. All models drew predictive power from space-time covariates that, based on past evidence, were expected to correlate to disease burden or reporting completeness. If the parametric relationships between covariates and these outcomes are incorrect, it may skew results in areas with extreme covariate values or little observed data. Each model also included spatial latent surfaces, which formalize the assumption that unobserved risk factors and covariates are likely to vary according to an underlying spatial structure: in other words, two neighboring observations in space are more likely to be similar than two distant observations, conditional on all observed fixed effects. This assumption, while reasonable for many ecological and disease phenomena,[@Diggle2016] can also over-smooth discontinuities across space, under-stating the true inequality between groups. Furthermore, these models are sensitive to priors for space-time variation:[@Wakefield2019] if strong priors are inaccurate, they can bias the model in the direction of existing expert opinion. For this reason, priors for highly uncertain quantities, such as those used to set reasonable bounds of CRVS bias in Chapter 2, should be thoughtfully considered and closely inspected before a model is implemented.

Separate from model implementation, translating model uncertainty into a policy setting can be challenging. Many policy processes are not developed with uncertainty in mind, and the prospect of simply interpreting summary estimates without uncertainty may be tempting from a decision-making perspective. In fact, uncertainty is arguably the most important aspect of small area models. New communication strategies are needed to intuitively demonstrate variability across many possible realizations of these spatial models.[@Patil2011]


## Future directions

The surveillance-based spatial models presented in this thesis offer several avenues for expansion and integration into health policymaking. In order to serve as a relevant decision-making tool for future policy, estimates must be continuously updated on timelines needed for effective public health response. In high-burden settings for tuberculosis, many National TB Control Programs operate on an annual cycle for disbursing funding and evaluating program effectiveness; in this situation, new case notifications can be integrated into estimates of TB burden on an annual or quarterly basis. On the other hand, estimates of excess mortality must be updated rapidly in order to quickly respond to outbreaks: in this case, near-continuous monitoring based on the model of the European Mortality Monitoring (EuroMoMo) group may be most appropriate. This style of monitoring requires additional data engineering to automate the integration of new mortality data into regularly-updated statistical models. Automated dashboards and other interactive visualizations may also facilitate the uptake of surveillance-based disease maps as policy tools; integration into existing health information tools, such as DHIS2 dashboards in many low-income countries, should be explored.

These models also offer opportunities for the spatial targeting of new surveys to increase precision and validate results in focal areas. Across Latin American countries with moderately high CRVS completeness, birth and mortality registration audits could be targeted in districts where estimated reporting completeness remains most uncertain in geostatistical models. Similarly, targeted infectious disease surveys could be conducted within districts where modeled estimates for disease prevalence and case notification completeness are both highly uncertain. These surveys could also be scheduled by district and year to maximize certainty relative to key programmatic goals.

In Chapters 3 and 5 of this thesis, concepts from space-time modeling were expanded to estimate variation across the additional dimension of age. Future research should expand further on this concept, exploring disaggregation across social categories to better understand variation in health inequality by place and over time. Geographical knowledge about variation in the social determinants of health can be formalized to quantify health inequities in a small-area context.


# Conclusions

This thesis attempts to redefine the role of modeling in countries with developing health surveillance systems. Previous advocacy for universal CRVS have argued that models have a deleterious crowding-out effect on CRVS improvement effects: in this conception, policymakers interpret models as an alternative source of data to raw health surveillance data, reducing the momentum to improve CRVS quality.[@Setel2007; @Tichenor2020] In this thesis, I have described a set of models that are explicitly designed to integrate health surveillance data into health decision-making processes at the country level. These models provide a new feedback mechanism by which improved health surveillance leads to more certain measurements and better health policy, strengthening the pragmatic argument for investing in health data systems. Additionally, as demonstrated in Uganda, these models can be designed to directly measure reporting completeness, offering a new tool for tracking surveillance completeness over a country. We also agree with the authors that CRVS systems are more than a data source: they are a process for guaranteeing legal and civil rights to a country's citizens.[@AbouZahr2015]

CRVS and national health data systems are required for long-lasting improvements in global health. As the primary data tool for national health systems, part of their utility rests on their ability to produce high-quality, timely, and disaggregated estimates of health status across a country's subpopulations. This thesis aims to strengthen the link between developing national health surveillance systems and improved health outcomes, leading to better health policies and a strong basis for human rights worldwide.


# References

<div id="refs"></div>
\newpage

